let express = require('express')
let router = express.Router()
let login = require('./api/login/login.js')
router.post('/login', login.post)
let user = require('./api/user/user.js')
router.get('/usersInfo',user.get)
let editUser = require('./api/user/editUser.js')
router.post('/editUser',editUser.post)
let admin=require('./api/admin/admin.js')
router.get('/adminsInfo',admin.get)
let addAdmin=require('./api/admin/addAdmin.js')
router.post('/addAdmin',addAdmin.post)
let deleAdmin=require('./api/admin/deleAdmin.js')
router.get('/deleAdmin',deleAdmin.get)
let editAdmin=require('./api/admin/editAdmin.js')
router.post('/editAdmin',editAdmin.post)
let goodsInfo=require('./api/goods/goodsInfo.js')
router.get('/goodsInfo',goodsInfo.get)
let goodsType=require('./api/goods/goodsType.js')
router.get('/goodsType',goodsType.get)
let goodsBrandType=require('./api/goods/goodsBrandType.js')
router.get('/goodsBrandType',goodsBrandType.get)
let goodsShow=require('./api/goods/goodsShow.js')
router.get('/goodsShow',goodsShow.get)
let goodsSizeType=require('./api/goods/goodsSizeType.js')
router.get('/goodsSizeType',goodsSizeType.get)
let addGoods=require('./api/goods/addGoods.js')
router.post('/addGoods',addGoods.post)
let deleteGoods=require('./api/goods/deleteGoods.js')
router.get('/deleteGoods',deleteGoods.get)
let batchDeleteGoods=require('./api/goods/batchDeleteGoods.js')
router.get('/batchDeleteGoods',batchDeleteGoods.get)
let editGoods=require('./api/goods/editGoods.js')
router.post('/editGoods',editGoods.post)
let issueOrder=require('./api/order/issueOrder.js')
router.get('/issueOrder',issueOrder.get)
let addIssueOrder=require('./api/order/addIssueOrder.js')
router.post('/addIssueOrder',addIssueOrder.post)
let getIssueOrderState=require('./api/order/getIssueOrderState.js')
router.get('/getIssueOrderState',getIssueOrderState.get)
let issueOrderStateChange=require('./api/order/issueOrderStateChange.js')
router.post('/issueOrderStateChange',issueOrderStateChange.post)
let editIssueOrder=require('./api/order/editIssueOrder.js')
router.post('/editIssueOrder',editIssueOrder.post)
let goodsNumberChange=require('./api/order/goodsNumberChange.js')
router.post('/goodsNumberChange',goodsNumberChange.post)
let getExpressType=require('./api/order/expressType.js')
router.get('/getExpressType',getExpressType.get)
let getCarousel=require('./api/carousel/carousel.js')
router.get('/getCarousel',getCarousel.get)
let getRecommend=require('./api/recommend/recommend.js')
router.get('/getRecommend',getRecommend.get)
module.exports = router